name: Create User Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest -m createuser
        continue-on-error: true